name: Automated Testing

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Clone external repo
        run: git clone https://github.com/ConesaLab/SQANTI3.git SQANTI3

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force

      - name: Set up Conda
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: SQANTI-sc_env.yml
          environment-name: SQANTI-sc_env
          cache-environment: true

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Run tests
        shell: bash -l {0}
        run: |
          micromamba activate SQANTI-sc_env
          echo "Current Conda environment: $(micromamba info --envs)"
          pytest tests/
